language: go
services:
  - docker
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "S5i9AVyLTdOPRE3vI2CAnKw77reKga9oe8JbFe7adSOjGRaRhPoiq6k6l11jdQqf/vNFxeJMXZWnLpXdLEdX/kp5i2HntLzFlErSd+0xWr8ZfVpQKraY2yl/UUxE78jihb48IOZdyVfp5CKRnu4DDHaFE5goOPakpkefmKyohn7R+W11NUsZnas+bOpV45QMc4j1UFvR00KjlJ/fNFot1nfRDW0/FG8pyM1qFZkKhlklAS97hpTDOwcM7yoYEBOlmrKeBakKtwr8/Nxl83tTEl8oMktd5+na4giAhfc9vw5h/D4Qyx5lVEd7znMXvcrTs7iLXGz/FCcMRrxrfmmSgw2XecLd3ldZ9bAIXolIFBI8LskWzdMtxZvvR+LwL9GZtxvFjnWZgwHAAC/uYSO/K0K/EWlX+H0Kn0Uuf3hnrlBH/A4BTn29eco5jSyR3smRFY83vu+V37t1ljYVMeoQNlPgOisEe+DMmYd10ADXEWisca0s/uq8YLAcsN61fwQ95yLP94CVczBK7gKuFFgAni+WvRIeTBjWQi3cllIq5ASiCPfFlUzX36uT4rMeftPWkV/docGkx3cDhV8PJhJMJa6y+kapqnlupbg2JxGUEs78/WBSNlHL1wlwJo/PabbnqqWiBXMMD/uo6F3w8eE1Kmghdre87ft3Gu4ekfA/DXU="
    # AWS_SECRET_ACCESS_KEY
    - secure: "qFVcPZI1z9KrHzjl8RexxlZD95n3CPH1qARZJvNLKBTzb0Fvv1p6uqnLmRGMsr+g9TuRovDP26Kaa3ggb9pYoNO3SWvKk80FFu4RKfDmelsnDoIbzMT3q59Dol7BMzKqTmc1YgOduepUvqeV3UraP7rPoo8s+xz6RDFDAx2ETWI5IV0FNIS5G00boE3UpMo/zfUdqH6VDTleLi+CCwIFSWDrD5bpFbnTtOVTDyIF4R9RNAQxuPyFWbG6zqXtSQKBeFwVQSPv2QWcE27sgZERjsJjlVURPK8rheGchmHxYCWzixxwSZVV/YmRRjKbMrhjrHz/CJtjSp2/uPGViZNwTQc3D2yr7aAuA2XXYpLj7QNLd6vjNeFwe9yc5FQFD4jBwIK2xRw/7p1yCVScIa/YK2NXwcU3eF1v/E/enuJQGeRULNl6ofjL0O7tufeb6LCWmN5ZP1Rp11qUFFqL/uSS/60Fi2VF6WbCDEHhwKrYm5ou1eqgR4ejc12VQNCsiPTOmc/oTxTTKE8YbL/lkJqyDE7M/QQUee65kC+OBQXq/V9HZhKEjN2kZqpkSRq5WFlbGiDhRAxNOtHnsFvFpS11dBUTVHbmtn+lRlNn3y0CNVCa3oS6hru+j7fVLfeCifFkMdTqkUVKVDaYDA0p5wj7JVjGiwGtAmczkMZvvSZ1R5o="
install:
  - go get -u -v github.com/spf13/hugo
script:
  - hugo
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: kalbas.it
    acl: private
    on:
      repo: "kalbasit/kalbas.it"
      branch: "deploy_to_s3"
