language: nix

script:
  - nix-shell --run 'hugo version'
  - nix-shell --run 'hugo --cleanDestinationDir --buildDrafts --buildExpired --buildFuture --stepAnalysis --templateMetrics --templateMetricsHints'

  # XXX: This is failing even without changes for some reason on the CI, but not on my local machine.
  # See the build here:
  # https://travis-ci.org/kalbasit/kalbas.it/builds/497998311?utm_source=github_status&utm_medium=notification
  #
  # - >
  #   if [[ "$( git --no-pager status --short | awk '$2 ~ /^docs/' | wc -l )" -gt 0 ]]; then
  #     echo ">>> Changes were detected after running \`hugo\`. Please run it, commit and push again"
  #     echo; echo; echo;
  #     git --no-pager diff
  #     exit 1
  #   fi
