baseUrl: /
enableRobotsTXT: true
footnoteReturnLinkContents: ↩
googleAnalytics: UA-82839578-2
languageCode: en-us
metaDataFormat: yaml
paginate: 5
publishDir: "docs"
theme: terminal

params:
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: blue
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 3

languages:
  en:
    title: Wael Nasreddine
    subtitle: Father - Entrepreneur - Architect - Engineer
    keywords: ''
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts

    params:
      logo:
        logoText: Kalbasit
        logoHomeLink: /

    menu:
      main:
      - identifier: about
        name: About
        url: /about
      - identifier: showcase
        name: Showcase
        url: /showcase
