baseurl: https://kalbas.it/
disqusShortname: kalbasit
enableRobotsTXT: true
footnotereturnlinkcontents: ↩
googleAnalytics: UA-82839578-2
languageCode: en-us
metaDataFormat: yaml
paginate: 10
params:
  author: Wael Nasredding
  avatar: images/kalbasit.jpg
  bio: Blogger - Engineer - Gopher
  copyright: Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice).
  date_format: 2006-01-02
  location: San Francisco Bay Area
  logo: images/logo.svg
  menu:
  - before: true
    label: Home
    link: /
  - before: false
    label: Tags
    link: tags/
  - before: false
    label: Categories
    link: categories/
  profile:
    follow_button: https://github.com/kalbasit
  site_description: "Tech blog, by Wael"
  widgets:
    categories: true
    recent_articles: true
    tag_cloud: true
    tags: true
permalinks:
  post: /:year/:month/:day/:slug
social:
  behance: ""
  bitbucket: ""
  codepen: ""
  deviantart: ""
  dribbble: ""
  facebook: kalbasit
  facebook_admin: ""
  flickr: ""
  foursquare: ""
  github: kalbasit
  gitlab: ""
  googleplus: ""
  instagram: ""
  jsfiddle: ""
  linkedin: "kalbasit"
  medium: ""
  pinterest: ""
  reddit: kalbasit
  slideshare: ""
  stackoverflow: "301730"
  tumblr: ""
  twitter: kalbasit
  twitter_domain: ""
  vimeo: ""
  vine: ""
  wordpress: ""
  xing: ""
  youtube: ""
theme: hugo-icarus-theme
title: kalbasit
