author: "Wael Nasreddine"
baseurl: "https://kalbas.it/"
disqusShortname: kalbasit
enableRobotsTXT: true
footnoteReturnLinkContents: ↩
googleAnalytics: UA-82839578-2
publishDir: "docs"
languageCode: en-us
metaDataFormat: yaml
paginate: 10
params:
  contentTypeName: "post"
  themeColor: blue
  showMenuItems: 3
languages:
  en:
    title: kalbasit
    subtitle: Wael Nasreddine
    keywords: ''
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts
    params:
      logo:
        logoText: λ kalbas.it
        logoHomeLink: /
    menu:
      main:
      - identifier: categories
        name: Categories
        url: /categories
      - identifier: hireme
        name: Hire Me
        url: /hireme
      - identifier: tags
        name: Tags
        url: /tags
permalinks:
  post: /:year/:month/:day/:slug
theme: hugo-theme-terminal
title: kalbasit
