baseUrl: /
languageCode: en-us
theme: terminal
paginate: 5

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: blue
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 3

languages:
  en:
    title: Kalbasit
    subtitle: Your site subtitle
    keywords: ''
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts

    params:
      logo:
        logoText: Terminal
        logoHomeLink: /

    menu:
      main:
      - identifier: about
        name: About
        url: /about
      - identifier: showcase
        name: Showcase
        url: /showcase
